# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/laurel_sprout-extra/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/laurel_sprout-extra

PRODUCT_PACKAGES += \
    GCamGo